[package]
name = "decoder"
version = "0.1.0"
edition = "2021"



[dependencies]
id3 = { workspace = true }
rust-crypto = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }